kind: pipeline
type: docker
name: build
steps:
- name: build
  image: golang:alpine
  pull: if-not-exists # always never
  environment:
    KEY: VALUE
  commands:
    - echo $KEY
    - pwd
    - ls
    - cp app.go main.go
    - go mod init
    - CGO_ENABLED=0 GOOS=linux go build main.go
    - ./main

trigger:
  branch:
  - main